// <auto-generated />
using System;
using EStoreRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EStoreRepository.Migrations
{
    [DbContext(typeof(BrandRepository))]
    [Migration("20260811103141_brandrepo")]
    partial class brandrepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstoreModel.Models.BrandModels.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e81f7680-07bd-4090-831c-d6d73a7656f1"),
                            Name = "Brand 1"
                        },
                        new
                        {
                            Id = new Guid("a59e44c4-197a-432c-a399-16808559c3b5"),
                            Name = "Brand 2"
                        },
                        new
                        {
                            Id = new Guid("76e61fbb-6474-4bff-ae02-1380163af3c5"),
                            Name = "Brand 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
